const fs = require("fs");
const path = require("path");

const originalRecommendedVenues = `const recommendedVenues = [
  {
    id: 1,
    name: "Champions Turf & Football Arena",
    location: "Powai, Mumbai",
    sport: "Football • Box Cricket",
    rating: "4.9",
    reviews: "128",
    price: "₹1,200",
    unit: "/ hr",
    badge: "PROMOTED",
    image: asset("/venues/champions_sports_arena_football.jpg"),
  },
  {
    id: 2,
    name: "Metro Sports Pitch & Stadium",
    location: "Bandra West, Mumbai",
    sport: "Cricket • Football",
    rating: "4.8",
    reviews: "96",
    price: "₹1,500",
    unit: "/ hr",
    badge: "POPULAR",
    image: asset("/venues/metro_sports_park_cricket.jpg"),
  },
  {
    id: 3,
    name: "Grand Playfield Badminton Club",
    location: "Andheri West, Mumbai",
    sport: "Badminton",
    rating: "4.9",
    reviews: "142",
    price: "₹600",
    unit: "/ hr",
    badge: "FAST FILLING",
    image: asset("/venues/grand_playfield_badminton.png"),
  },
  {
    id: 4,
    name: "GreenPark Pro Tennis Court",
    location: "Juhu, Mumbai",
    sport: "Lawn Tennis",
    rating: "4.7",
    reviews: "64",
    price: "₹1,000",
    unit: "/ hr",
    badge: "TOP RATED",
    image: asset("/venues/new_tennis_turf.png"),
  },
  {
    id: 5,
    name: "Spike & Jump Volleyball Arena",
    location: "South Mumbai",
    sport: "Volleyball",
    rating: "5.0",
    reviews: "210",
    price: "₹1,800",
    unit: "/ hr",
    badge: "FEATURED",
    image: asset("/venues/new_volleyball_turf.png"),
  },
  {
    id: 6,
    name: "Shivaji Park Turf",
    location: "Kothrud, Pune",
    sport: "Cricket • Football",
    rating: "4.6",
    reviews: "82",
    price: "₹1,100",
    unit: "/ hr",
    badge: "POPULAR",
    image: asset("/venues/champions_sports_arena_football.jpg"),
  },
  {
    id: 7,
    name: "Marina Sports Hub",
    location: "Adyar, Chennai",
    sport: "Badminton • Tennis",
    rating: "4.7",
    reviews: "56",
    price: "₹800",
    unit: "/ hr",
    badge: "NEW",
    image: asset("/venues/grand_playfield_badminton.png"),
  },
  {
    id: 8,
    name: "Deccan Sports Arena",
    location: "Viman Nagar, Pune",
    sport: "Football • Basketball",
    rating: "4.8",
    reviews: "115",
    price: "₹1,500",
    unit: "/ hr",
    badge: "PROMOTED",
    image: asset("/venues/new_tennis_turf.png"),
  },
  {
    id: 9,
    name: "Hinjewadi IT Park Pitch",
    location: "Hinjewadi, Pune",
    sport: "Box Cricket",
    rating: "4.5",
    reviews: "95",
    price: "₹900",
    unit: "/ hr",
    badge: "FAST FILLING",
    image: asset("/venues/metro_sports_park_cricket.jpg"),
  },
  {
    id: 10,
    name: "Wakad Pro Badminton Club",
    location: "Wakad, Pune",
    sport: "Badminton",
    rating: "4.9",
    reviews: "210",
    price: "₹650",
    unit: "/ hr",
    badge: "TOP RATED",
    image: asset("/venues/grand_playfield_badminton.png"),
  },
];`;

const homepagePath = path.join(__dirname, "src", "app", "components", "home", "homepage.jsx");
let content = fs.readFileSync(homepagePath, "utf-8");

// Replace array
const arrayRegex = /const recommendedVenues = \[[\s\S]*?\];/;
content = content.replace(arrayRegex, originalRecommendedVenues);

fs.writeFileSync(homepagePath, content, "utf-8");
console.log("Successfully reverted turfs to the exact previous state.");
