import { motion } from "motion/react";
import { Search, Plus, Filter } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "../../components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "../../components/ui/table";
import { Badge } from "../../components/ui/badge";
import { Button } from "../../components/ui/button";
import { Input } from "../../components/ui/input";

export function AdminReports() {
  return (
    <motion.div 
      initial={{ opacity: 0, y: 10 }} 
      animate={{ opacity: 1, y: 0 }}
      className="space-y-6"
    >
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">System Reports</h1>
          <p className="text-muted-foreground">Generate and download platform reports.</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline"><Filter className="h-4 w-4 mr-2" /> Filter</Button>
          <Button><Plus className="h-4 w-4 mr-2" /> Add New</Button>
        </div>
      </div>

      <Card>
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between">
            <CardTitle>Overview</CardTitle>
            <div className="relative w-64">
              <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
              <Input placeholder="Search records..." className="pl-9 bg-muted/50" />
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <div className="rounded-md border overflow-hidden">
            <Table>
              <TableHeader className="bg-muted/50">
                <TableRow>
                  <TableHead>Report Name</TableHead>
                  <TableHead>Generated By</TableHead>
                  <TableHead>Date</TableHead>
                  <TableHead>Size</TableHead>
                  <TableHead>Action</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell>Q3 Financials</TableCell>
                  <TableCell>System</TableCell>
                  <TableCell>Oct 01, 2024</TableCell>
                  <TableCell>2.4 MB</TableCell>
                  <TableCell>Download</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>User Growth 2024</TableCell>
                  <TableCell>Admin</TableCell>
                  <TableCell>Oct 15, 2024</TableCell>
                  <TableCell>1.1 MB</TableCell>
                  <TableCell>Download</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Turf Performance</TableCell>
                  <TableCell>System</TableCell>
                  <TableCell>Oct 20, 2024</TableCell>
                  <TableCell>3.5 MB</TableCell>
                  <TableCell>Download</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Refund Log</TableCell>
                  <TableCell>System</TableCell>
                  <TableCell>Oct 24, 2024</TableCell>
                  <TableCell>0.8 MB</TableCell>
                  <TableCell>Download</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>
    </motion.div>
  );
}
